name: Reusable Workflow
on:
    workflow_call
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Output information
              run: echo "Deploying ... & this is a reusable workflow called by ${{ github.actor }}"