name: Website Deployment
on:
    push:
        branches:
            - main
env:
  AUTHOR: ${{ github.actor }}
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v7
            - name: Cache Dependencies
              uses: actions/cache@v6
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Lint code
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v7
            - name: Cache Dependencies
              uses: actions/cache@v6
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v7
            - name: Cache Dependencies
              uses: actions/cache@v6
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Build website
              run: npm run build
            - name: Upload build artifacts
              uses: actions/upload-artifact@v7
              with:
                name: dist-files
                path: dist
                if-no-files-found: error
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get Build Artifacts
              uses: actions/download-artifact@v7
              with:
                name: dist-files
            - name: List dist's contents
              run: ls -la dist
            - name: Deploy to GitHub Pages
              run: echo "Deploying by $AUTHOR..."