name: Website Deployment
on:
  workflow_dispatch:
    # push:
    #     branches:
    #         - main
env:
  AUTHOR: ${{ github.actor }}
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v7
            - name: Set up Node
              uses: actions/setup-node@v7
              with:
                node-version: 22
            - name: Cache Dependencies
              uses: actions/cache@v6
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Lint code
              run: npm run lint:ci
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v7
            - name: Set up Node
              uses: actions/setup-node@v7
              with:
                node-version: 22
            - name: Cache Dependencies
              uses: actions/cache@v6
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Run tests
              continue-on-error: true
              id: run-tests
              run: npm test
            - name: Upload test report
              uses: actions/upload-artifact@v7
              with:
                name: test-report
                path: test.json
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v7
            - name: Set up Node
              uses: actions/setup-node@v7
              with:
                node-version: 22
            - name: Cache Dependencies
              uses: actions/cache@v6
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Build website
              run: npm run build
            - name: Upload build artifacts
              uses: actions/upload-artifact@v7
              with:
                name: dist-files
                path: dist
                if-no-files-found: error
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get Build Artifacts
              uses: actions/download-artifact@v7
              with:
                name: dist-files
                path: dist
            - name: List dist's contents
              run: ls -la dist
            - name: Deploy to GitHub Pages
              run: echo "Deploying by $AUTHOR..."
    report:
        needs: [lint, test, build, deploy]
        runs-on: ubuntu-latest
        if: failure() || needs.lint.result == 'failure' || needs.test.result == 'failure' || needs.build.result == 'failure' || needs.deploy.result == 'failure'
        steps:
            - name: Print Report
              run: |
                echo "Lint: ${{ needs.lint.result }}"
                echo "Test: ${{ needs.test.result }}"
                echo "Build: ${{ needs.build.result }}"
                echo "Deploy: ${{ needs.deploy.result }}"
                echo "Something goes wrong, please check the logs for details."
